USE partnerdb;
INSERT INTO Partners
(Name, ContactInfo, PartnerType, Discriminator, Stars, LisenceNumber, TransportType)
VALUES
('Hotel Aurora', 'aurora@mail.com', 'Hotel', 'partnerHotel', 5, NULL, NULL),
('Hotel Sunrise', 'sunrise@mail.com', 'Hotel', 'partnerHotel', 4, NULL, NULL),
('Hotel Sunset', 'sunset@mail.com', 'Hotel', 'partnerHotel', 3, NULL, NULL),
('Hotel Ocean', 'ocean@mail.com', 'Hotel', 'partnerHotel', 5, NULL, NULL),
('Hotel Sky', 'sky@mail.com', 'Hotel', 'partnerHotel', 4, NULL, NULL),
('Hotel Comfort', 'comfort@mail.com', 'Hotel', 'partnerHotel', 3, NULL, NULL),
('Hotel Relax', 'relax@mail.com', 'Hotel', 'partnerHotel', 4, NULL, NULL),
('Hotel Royal', 'royal@mail.com', 'Hotel', 'partnerHotel', 5, NULL, NULL),
('Hotel Budget', 'budget@mail.com', 'Hotel', 'partnerHotel', 2, NULL, NULL),
('Hotel City', 'city@mail.com', 'Hotel', 'partnerHotel', 3, NULL, NULL),
('Hotel Central', 'central@mail.com', 'Hotel', 'partnerHotel', 4, NULL, NULL),
('Hotel Plaza', 'plaza@mail.com', 'Hotel', 'partnerHotel', 5, NULL, NULL),
('Hotel Garden', 'garden@mail.com', 'Hotel', 'partnerHotel', 4, NULL, NULL),
('Hotel Park', 'park@mail.com', 'Hotel', 'partnerHotel', 3, NULL, NULL),
('Hotel River', 'river@mail.com', 'Hotel', 'partnerHotel', 4, NULL, NULL),
('Hotel Lake', 'lake@mail.com', 'Hotel', 'partnerHotel', 5, NULL, NULL),
('Hotel Forest', 'forest@mail.com', 'Hotel', 'partnerHotel', 3, NULL, NULL),
('Hotel Hill', 'hill@mail.com', 'Hotel', 'partnerHotel', 4, NULL, NULL),
('Hotel Grand', 'grand@mail.com', 'Hotel', 'partnerHotel', 5, NULL, NULL),
('Hotel Elite', 'elite@mail.com', 'Hotel', 'partnerHotel', 5, NULL, NULL),
('Hotel Nova', 'nova@mail.com', 'Hotel', 'partnerHotel', 4, NULL, NULL),
('Hotel Star', 'star@mail.com', 'Hotel', 'partnerHotel', 3, NULL, NULL),
('Hotel Moon', 'moon@mail.com', 'Hotel', 'partnerHotel', 4, NULL, NULL),
('Hotel Sun', 'sun@mail.com', 'Hotel', 'partnerHotel', 5, NULL, NULL),
('Hotel Cloud', 'cloud@mail.com', 'Hotel', 'partnerHotel', 4, NULL, NULL),
('Hotel Breeze', 'breeze@mail.com', 'Hotel', 'partnerHotel', 3, NULL, NULL),
('Hotel Light', 'light@mail.com', 'Hotel', 'partnerHotel', 4, NULL, NULL),
('Hotel Wave', 'wave@mail.com', 'Hotel', 'partnerHotel', 5, NULL, NULL),
('Hotel Pearl', 'pearl@mail.com', 'Hotel', 'partnerHotel', 5, NULL, NULL),
('Hotel Stone', 'stone@mail.com', 'Hotel', 'partnerHotel', 3, NULL, NULL),
('Hotel Sand', 'sand@mail.com', 'Hotel', 'partnerHotel', 4, NULL, NULL),
('Hotel Ice', 'ice@mail.com', 'Hotel', 'partnerHotel', 3, NULL, NULL),
('Hotel Fire', 'fire@mail.com', 'Hotel', 'partnerHotel', 5, NULL, NULL),
('Hotel Wind', 'wind@mail.com', 'Hotel', 'partnerHotel', 4, NULL, NULL),
('Hotel Earth', 'earth@mail.com', 'Hotel', 'partnerHotel', 3, NULL, NULL),
('Hotel Metal', 'metal@mail.com', 'Hotel', 'partnerHotel', 4, NULL, NULL),
('Hotel Wood', 'wood@mail.com', 'Hotel', 'partnerHotel', 3, NULL, NULL),
('Hotel Crystal', 'crystal@mail.com', 'Hotel', 'partnerHotel', 5, NULL, NULL),
('Hotel Diamond', 'diamond@mail.com', 'Hotel', 'partnerHotel', 5, NULL, NULL),
('Hotel Silver', 'silver@mail.com', 'Hotel', 'partnerHotel', 4, NULL, NULL),

('TravelPro', 'travelpro@mail.com', 'Operator', 'partnerOperator', NULL, 'B001-10001-01/100000001', NULL),
('WorldTours', 'world@mail.com', 'Operator', 'partnerOperator', NULL, 'B002-10002-02/100000002', NULL),
('EasyTrip', 'easy@mail.com', 'Operator', 'partnerOperator', NULL, 'B003-10003-03/100000003', NULL),
('SkyTravel', 'skytravel@mail.com', 'Operator', 'partnerOperator', NULL, 'B004-10004-04/100000004', NULL),
('SunTour', 'suntour@mail.com', 'Operator', 'partnerOperator', NULL, 'B005-10005-05/100000005', NULL),
('OceanTrip', 'oceantrip@mail.com', 'Operator', 'partnerOperator', NULL, 'B006-10006-06/100000006', NULL),
('CityTours', 'citytours@mail.com', 'Operator', 'partnerOperator', NULL, 'B007-10007-07/100000007', NULL),
('GlobalTravel', 'global@mail.com', 'Operator', 'partnerOperator', NULL, 'B008-10008-08/100000008', NULL),
('DreamTrip', 'dream@mail.com', 'Operator', 'partnerOperator', NULL, 'B009-10009-09/100000009', NULL),
('PrimeTours', 'prime@mail.com', 'Operator', 'partnerOperator', NULL, 'B010-10010-10/100000010', NULL),
('EliteTravel', 'elite@mail.com', 'Operator', 'partnerOperator', NULL, 'B011-10011-11/100000011', NULL),
('FastTrip', 'fast@mail.com', 'Operator', 'partnerOperator', NULL, 'B012-10012-12/100000012', NULL),
('HolidayPro', 'holiday@mail.com', 'Operator', 'partnerOperator', NULL, 'B013-10013-13/100000013', NULL),
('MegaTours', 'mega@mail.com', 'Operator', 'partnerOperator', NULL, 'B014-10014-14/100000014', NULL),
('SmartTravel', 'smart@mail.com', 'Operator', 'partnerOperator', NULL, 'B015-10015-15/100000015', NULL),
('BestTrip', 'best@mail.com', 'Operator', 'partnerOperator', NULL, 'B016-10016-16/100000016', NULL),
('EcoTravel', 'eco@mail.com', 'Operator', 'partnerOperator', NULL, 'B017-10017-17/100000017', NULL),
('UrbanTours', 'urban@mail.com', 'Operator', 'partnerOperator', NULL, 'B018-10018-18/100000018', NULL),
('RouteTravel', 'route@mail.com', 'Operator', 'partnerOperator', NULL, 'B019-10019-19/100000019', NULL),
('OpenWorld', 'open@mail.com', 'Operator', 'partnerOperator', NULL, 'B020-10020-20/100000020', NULL),
('AlphaTravel', 'alpha@mail.com', 'Operator', 'partnerOperator', NULL, 'B021-10021-21/100000021', NULL),
('BetaTours', 'beta@mail.com', 'Operator', 'partnerOperator', NULL, 'B022-10022-22/100000022', NULL),
('GammaTrip', 'gamma@mail.com', 'Operator', 'partnerOperator', NULL, 'B023-10023-23/100000023', NULL),
('DeltaTravel', 'delta@mail.com', 'Operator', 'partnerOperator', NULL, 'B024-10024-24/100000024', NULL),
('SigmaTours', 'sigma@mail.com', 'Operator', 'partnerOperator', NULL, 'B025-10025-25/100000025', NULL),
('VectorTrip', 'vector@mail.com', 'Operator', 'partnerOperator', NULL, 'B026-10026-26/100000026', NULL),
('OrbitTravel', 'orbit@mail.com', 'Operator', 'partnerOperator', NULL, 'B027-10027-27/100000027', NULL),
('NovaTours', 'nova@mail.com', 'Operator', 'partnerOperator', NULL, 'B028-10028-28/100000028', NULL),
('AtlasTravel', 'atlas@mail.com', 'Operator', 'partnerOperator', NULL, 'B029-10029-29/100000029', NULL),
('ZenithTrip', 'zenith@mail.com', 'Operator', 'partnerOperator', NULL, 'B030-10030-30/100000030', NULL),

('Sky Airlines', 'air@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'flight'),
('Cloud Wings', 'cloud@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'flight'),
('Jet Express', 'jet@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'flight'),
('Bus Express', 'bus@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'bus'),
('City Bus', 'citybus@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'bus'),
('InterBus', 'inter@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'bus'),
('Railway Corp', 'rail@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'train'),
('Fast Train', 'fasttrain@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'train'),
('Metro Line', 'metro@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'train'),
('Cargo Rail', 'cargo@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'train'),
('Sea Lines', 'sea@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'ship'),
('Oceanic', 'oceanic@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'ship'),
('Blue Water', 'blue@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'ship'),
('Ferry One', 'ferry@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'ship'),
('Port Travel', 'port@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'ship'),
('AirJet', 'airjet@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'flight'),
('FlyFast', 'fly@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'flight'),
('BusWay', 'busway@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'bus'),
('RoadLine', 'road@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'bus'),
('Night Train', 'night@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'train'),
('Silver Rail', 'silverrail@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'train'),
('Golden Bus', 'goldbus@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'bus'),
('Aqua Ship', 'aqua@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'ship'),
('Wave Ferry', 'wave@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'ship'),
('Storm Lines', 'storm@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'ship'),
('Eagle Air', 'eagle@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'flight'),
('Falcon Air', 'falcon@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'flight'),
('Rapid Bus', 'rapid@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'bus'),
('Express Rail', 'express@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'train'),
('Harbor Lines', 'harbor@mail.com', 'Transport', 'partnerTransport', NULL, NULL, 'ship');
