// <auto-generated />
using MicroservicePartner.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroservicePartner.Migrations
{
    [DbContext(typeof(PartnerContext))]
    [Migration("20251028160838_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicroservicePartner.Models.Partner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partners");

                    b.HasDiscriminator().HasValue("Partner");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MicroservicePartner.Models.partnerHotel", b =>
                {
                    b.HasBaseType("MicroservicePartner.Models.Partner");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("partnerHotel");
                });

            modelBuilder.Entity("MicroservicePartner.Models.partnerOperator", b =>
                {
                    b.HasBaseType("MicroservicePartner.Models.Partner");

                    b.Property<string>("LisenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("partnerOperator");
                });

            modelBuilder.Entity("MicroservicePartner.Models.partnerTransport", b =>
                {
                    b.HasBaseType("MicroservicePartner.Models.Partner");

                    b.Property<int>("TransportType")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("partnerTransport");
                });
#pragma warning restore 612, 618
        }
    }
}
